### ISSUE TITLE
link je paginas

### ISSUE THREAD

**Issue by kosterm14** [zombie0youssra/server-side-visual-thinking#3]
![image](https://user-images.githubusercontent.com/61830362/224286686-f94d21cb-0f0a-4ff1-adf5-789e89a56b5a.png)

in je index.js moet je referen naar de pagina (ipv beschrijving doe je de naam van je eigen pagina)

![image](https://user-images.githubusercontent.com/61830362/224284567-0770c993-3b6b-4df7-9e51-473a2504912a.png)

en dan een <a> ernaar

![image](https://user-images.githubusercontent.com/61830362/224284605-73270e4b-c704-425d-aeac-36a241daccd5.png)

**Comment by zombie0youssra** [comment]
thanks is gelukt
